-- Run this in your Supabase SQL Editor

-- [WARNING] This will DELETE existing data in these tables. 
DROP TABLE IF EXISTS public.nation_banners;
DROP TABLE IF EXISTS public.banners;
DROP TABLE IF EXISTS public.admin_access;

-- 1. Create Nation Banners Table
create table public.nation_banners (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text,
  url text not null,
  banner_link text,
  start_date text,
  nation_key text not null
);

-- 2. Create Admin Access Table
create table public.admin_access (
  email text primary key,
  access_key text,
  role text default 'admin'
);

-- 3. Enable RLS
alter table public.nation_banners enable row level security;
alter table public.admin_access enable row level security;

-- 4. Policies (UPDATED TO FIX ERROR)
-- Vì tính năng đăng nhập bằng Key không tạo Session thực của Supabase,
-- ta cần cho phép 'anon' (khách) cũng có thể ghi dữ liệu nếu họ có code Admin.
-- Lưu ý: Cách này tiện lợi nhưng kém bảo mật hơn.

-- Cho phép tất cả mọi người đọc/ghi (Do logic bảo mật đã nằm ở file js)
create policy "Allow all actions for everyone" on public.nation_banners for all using (true) with check (true);

create policy "Allow read access for Admin List" on public.admin_access for select using (true);
-- Không cho phép user thường ghi đè danh sách Admin
create policy "Allow insert/update for Service Role only" on public.admin_access for all using (false); 

-- Seed data
insert into public.admin_access (email, access_key) values ('blazehunter01062008@gmail.com', 'admin123');
